controller_list:
  - name: fake_robot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - First_joint
      - Second_joint
      - Third_joint
initial:  # Define initial robot poses per group
  - group: robot_arm
    pose: home