robot_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - First_joint
    - Second_joint
    - Third_joint
  gains:
    First_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Second_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Third_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1